### ISSUE TITLE
Checklist to address changes due to move to OpenJS Foundation

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#311]
There are a number of things we need to address due to the move to the OpenJS Foundation. 
In particular based on the governance in: 

* https://github.com/nodejs/bootstrap/blob/master/proposals/stage-2/CPC_CHARTER/CPC-CHARTER.md
* https://github.com/nodejs/bootstrap/blob/master/proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
* https://github.com/nodejs/bootstrap/tree/master/proposals/stage-3/COMMUNITY_BOARD_REPRESENTATION

- [x] Agree on how we will elect representatives to the CPC.  There are 2 for the Node.js project. My 
  initial proposal is that we mirror what we do for existing Board representation and have one from
  the TSC and one from the Community Committee.  We could adjust that if we think it makes sense 
  though so potentially worth some thought/discussion.
- [ ] Agree on timeline for electing CPC representatives
- [ ]  Confirm the process/timelime for selection of Board representative. Node.js should likely
  have one for the first year although this needs to be confirmed after formation of the CPC.
  the CPC guidance says
   * the Node.js project will elect one Board representative from either the TSC or Community 
     Committee. The representative will be selected through a vote of the members of the Node.js 
     organization.
- [ ] Update TSC Charter and governance
- [ ] Update CommComm Charter and governance
- [ ] Update Code of conduct references
- [ ] Update moderation policy to reflect escalation as outline in 
  FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
- [ ] Figure out travel fund administration in the new foundation and update https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md
- [ ] Transition for individual membership program to be under CPC?

- [ ] will continue to build out list but saving so I don't lose what I have so far :)

- [ ] Update any references to the Node.js Foundation in our docs.

**Comment by Trott** [comment]
- [ ] Figure out travel fund administration in the new foundation and update https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md

**Comment by mhdawson** [comment]
@Trott, thanks added to list above

**Comment by mcollina** [comment]
Should we schedule a meeting to tackle those issues? They seems very broad tasks.

**Comment by nobodydevrus** [comment]
@mcollina I thought we could start to discuss in the TSC meeting today and figure out some next steps.

**Comment by mhdawson** [comment]
@mcollina I thought we could start to discuss in the TSC meeting today and figure out some next steps.

**Comment by joesepi** [comment]
Individual Membership should move from the CommComm to new Foundation work https://github.com/nodejs/community-committee/issues/423

**Comment by WaleedAshraf** [comment]
maybe update the title of Node.js Foundation account on medium: https://medium.com/@nodejs

**Comment by keywordnew** [comment]
The OpenJS Foundation has it's own Github and Twitter.

We'll continue to own those. But maybe we'll want to not reference the Node.js Foundation ;)

**Comment by Trott** [comment]
Mentioned/briefly-discussed at today's TSC meeting. Removing the `tsc-agenda` label. Feel free to add it back if it should stay.

**Comment by mhdawson** [comment]
@mcollina scheduling a meeting to discuss moving forward on these makes sense.  Do you want to do that?  If not I'll try to set it up once I get a chance.

**Comment by mcollina** [comment]
@mhdawson I'm going to propose Wednesday 10 🚀  or Thursday 18th at 17:00 UTC 🎉 . Please vote.

**Comment by amiller-gh** [comment]
Also removed the `cc-agenda` label since we discussed it last time. We'll add it back if there are action items from the dedicated meeting.

**Comment by mhdawson** [comment]
Both times work for me but I'd prefer Wednesday 10th (closer to now)

**Comment by Trott** [comment]
It seems like this checklist is not being used so I'll close this, but feel free to re-open if we're going to start using it again.
