### ISSUE TITLE
Tracking issue for creating LFX crowdfunding account to accept bounties

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#746]
The TSC discussed/agreed to create an LFX crowdfunding account to accept the Project Part of the Hacker One bug bounties.

This issue is to track/share progress on that. At this point I believe we need to do the following:

- [x] Create an LFX Account that can be used to create the crowdfunding account. 
  Currently they don't have any notion of teams so it needs to its own email
  - [x] add email alias `nodejs-lfx-bounty` to https://github.com/nodejs/email/blob/main/iojs.org/aliases.json
  - [x] create the account
  - [x] add password to Node.js 1password account
- [x] Let hacker one know which account to forward the $ to
- [x] Define the governance/process for the project/TSC allocating the funds.  Approval should
       be by TSC and TSC chair pushes button in LFX account to make payout after approved
       by the TSC. - PR for governance - https://github.com/nodejs/TSC/pull/1313
- [ ] Review how its working after 3 and 6 months

**Comment by mhdawson** [comment]
PR to add email alias - https://github.com/nodejs/email/pull/202/files

**Comment by mhdawson** [comment]
Created the LFX Account and then requested the crowdfunding account. It's currently pending.
