### ISSUE TITLE
Sunset of the "Nodejs.dev" team and changes on the Website WG

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#772]
Hey all 👋, as I was talking with @Trott a few days ago, I believe that the "Node.js Website Redesign" WG achieved its ultimate goal, and with the PR nodejs/nodejs.org#4991 we will ultimately start the hand-off from the codebase of nodejs.dev into the current repository of nodejs.org (By starting the migration of style, content, translations, components and et cetera).

This ultimately means we can sunset the "Website Redesign Team". This would mean the ownership of the "nodejs.dev" repository would be transferred to the Website WG, which makes sense.

We can move the active members of the "Nodejs.dev" Team to the Website WG if they're willing and active. Ultimately all other members will be removed from the team, and if that's their only team on the org, they will be removed from the org (I'm assuming this happens if they're removed from all teams). This also means the README.md would get updated to remove the "active members" to "emeritus members" as the project will no longer be active.

With the removal of the Team and the fact that we're soon starting to hand off code from nodejs.dev to nodejs.org, I believe the repository (nodejs.dev) should stop receiving new feature requests but still support bug fixes and implementation of existing needs until we finish transferring everything to nodejs.org, which then ultimately means, archiving the repository.

I've created this issue to keep track of these actions and confirm with the TSC that this proposed plan is 🆗 for the TSC.

Finally, I'd also like to express my interest that the Website WG needs to be audited and non-active members removed. This would allow us to understand better the current needs and how many contributors we can count on. Ultimately I want to start going around the web and get newcomers.

### To-Do List

- [x] Get Approval from the TSC
- [x] Create an announcement Issue on Nodejs.dev about the sunset of the Team
- [x] Audit the Website WG current members
- [ ] Move active members (based on their interest expressed in this issue) to the Website WG
- [ ] Delete the "nodejs.dev" Team and change ownership to Website WG

cc @nodejs/tsc @nodejs/website @nodejs/nodejs-dev

**Comment by Trott** [comment]
Although I'm not sure about what the timeline should be, broadly, I think this is the way to go.

I forget if the website group is in fact a chartered WG or if it's simply a GitHub team. If it's a WG, it can/should probably be de-chartered or re-chartered to update exactly what is delegated there.

**Comment by ovflowd** [comment]
I also have no idea if The Website is an actual WG, I feel it is, but not sure.

**Comment by ovflowd** [comment]
@Trott as it seems, the Website WG is not a WG anymore, it got decharted long time ago https://github.com/nodejs/TSC/pull/761

**Comment by ovflowd** [comment]
Hey, @Trott, after checking the current members of @nodejs/nodejs.dev, it feels like all the members that are there are still active members and can be transferred to the @nodejs/website team, TL;DR

Can we invite @rodion-arr @shanpriyan to the Website Team? The only one I'm unsure if they're still active/willing to be part of the team is @manishprivet (Manish, let me know if you still want to be part of the team). Then we can finally archive the team.

From the @nodejs/website team, we can remove everybody except for @aymen94 @MaledongGit @benhalverson @bnb and, of course, the members of the team that are also part of the TSC.

Please, if anybody from the Website Team does **not** want to stay in the team, comment here. Same as the opposite, if you're not active but want to stay in the team, please comment here (and let us know why you'd like to stay)

**Comment by manishprivet** [comment]
Hey @ovflowd, apologies to the team for being inactive for the last few months, I had some ups and downs 😅. I'm going to come back to contribute very soon, and I definitely want to be a part of the team. Thanks!

**Comment by Trott** [comment]
> Hey, @Trott, after checking the current members of @nodejs/nodejs-dev, it feels like all the members that are there are still active members and can be transferred to the @nodejs/website team, TL;DR
> 
> Can we invite @rodion-arr @shanpriyan to the Website Team? The only one I'm unsure if they're still active/willing to be part of the team is @manishprivet (Manish, let me know if you still want to be part of the team). Then we can finally archive the team.
> 
> From the @nodejs/website team, we can remove everybody except for @aymen94 @MaledongGit @benhalverson @bnb and, of course, the members of the team that are also part of the TSC.
> 
> Please, if anybody from the Website Team does **not** want to stay in the team, comment here. Same as the opposite, if you're not active but want to stay in the team, please comment here (and let us know why you'd like to stay)

@ovflowd You are now a maintainer of the Website team, so I'll leave it to you to make these changes, but if you'd rather I get involved or if you have any concerns/questions, feel free to comment here or DM me on the OpenJS Slack. Thanks!

**Comment by XhmikosR** [comment]
I also had some real life issues to deal with so I haven't been very active until recently. I understand the need for cleanup and since I can't guarantee when I'll be able to contribute again, you can remove me.

Great job moving things forward to everyone involved!

**Comment by ovflowd** [comment]
@Trott members from .dev transferred to the website team. And all inactive members from the Website Team (that are not part of the TSC) also removed. ✅

**Comment by Trott** [comment]
> @Trott members from .dev transferred to the website team. And all inactive members from the Website Team (that are not part of the TSC) also removed. ✅

The nodejs.dev team has been deleted. Also, members removed from the website team that aren't in any other teams have been removed from the org.
